# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1twU-gzWjNSoQQVPosh4Eu7aLU6s48iRR
"""

from transaction import Transaction

ts = Transaction()

def main():
  """
  Fungsi sebagai interface agar pembeli tidak perlu ngoding
  """
  while True:
    print('\t\n\n\nSELAMAT DATANG DI TOKO KAMI\n')
    print('Silahkan Pilih Menu di Bawah Ini')
    print('1. Tambah Item/Barang')
    print('2. Ubah Item/Barang')
    print('3. Hapus Item/Barang')
    print('4. Check Item/Barang')
    print('5. Total Bayar')
    print('0. Batal')
    try:
      a = int(input('Masukan Pilihan Angka: '))
      if type(a) == int:
        if a == 1:
          while True:
            while True:
              try:
                a = str(input('Nama item/barang : '))
                b = int(input('Jumlah item/barang : '))
                c = int(input('Harga per item/barang : '))
                if type(a) == str and type(b) == int and type(c) == int:
                  ts.add_item(a, b, c)
                  break
              except:
                print('\nMohon ulangi!. Pastikan:\n*Nama item harus huruf!\n*Jumlah item harus bilangan bulat!\n*Harga item harus bilangan bulat!\n')
            print(f'\nItem yang dibeli adalah: {ts.simpan_item}')
            d = int(input('\nKetik selain 0 untuk tambah item dan ketik 0 jika sudah!: '))
            if d == 0 and type(d) == int:
              break
        elif a == 2:
          if len(ts.simpan_item) >= 1:
            while True:
              try:
                print('\n1. Ubah Nama Item/Barang')
                print('2. Ubah Jumlah Item/Barang')
                print('3. Ubah Harga Peritem/Barang')
                print('0. Kembali')
                b = int(input('Masukan Pilihan Angka: '))
                if b == 1:
                  while True:
                    print(f'\nItem yang dibeli adalah: {ts.simpan_item}')
                    e = str(input('Masukan nama item yang ingin diubah!: '))
                    try:
                      if e in ts.simpan_item:
                        f = str(input('Masukan perubahan nama item!: '))
                        ts.update_item_name(e, f)
                        break
                    except:
                      print('Mohon ulangi!. Pastikan nama item sudah sesuai dan ada di daftar belanja!')
                elif b == 2:
                  while True:
                    print(f'\nItem yang dibeli adalah: {ts.simpan_item}')
                    g = str(input('Masukan nama item yang ingin diubah jumlahnya!: '))
                    try:
                      if g in ts.simpan_item:
                        h = int(input('Masukan jumlah item terbaru!: '))
                        if type(h) == int:
                          ts.update_item_qty(g, h)
                          break
                    except:
                      print('\nMohon ulangi!. Pastikan: \n*nama item sudah sesuai dan ada di daftar belanja!\n*Pastikan jumlah item berupa bilangan bulat')
                elif b == 3:
                  while True:
                    print(f'\nItem yang dibeli adalah: {ts.simpan_item}')
                    i = str(input('Masukan nama item yang ingin diubah harganya!: '))
                    try:
                      if g in ts.simpan_item:
                        j = int(input('Masukan harga peritem terbaru!: '))
                        if type(j) == int:
                          ts.update_item_price(i, j)
                          break
                    except:
                      print('\nMohon ulangi!. Pastikan: \n*nama item sudah sesuai dan ada di daftar belanja!\n*Pastikan harga item berupa bilangan bulat')
                elif b == 0:
                  break
                else:
                  print('\nMohon ulangi!. Pastikan:\n*Bilangan yang Anda masukan bilangan bulat 1-4!')
              except:
                print('\nMohon ulangi!. Pastikan:\n*Bilangan yang Anda masukan bilangan bulat!')
          else:
            print('Maaf, item/barang belum ditambahkan. Silahkan pilih menu tambah item/barang!')
        elif a == 3:
          if len(ts.simpan_item) >= 1:
            while True:
              try:
                print('\n1. Hapus satu Item/Barang')
                print('2. Hapus seluruh Item/Barang')
                print('0. Kembali')
                c = int(input('Masukan Pilihan Angka: '))
                if c == 1:
                  while True:
                    print(f'\nItem yang dibeli adalah: {ts.simpan_item}')
                    k = str(input('Masukan nama item yang ingin dihapus!: '))
                    if k in ts.simpan_item:
                      ts.delete_item(k)
                      break
                    else:
                      print('Mohon ulangi. Pastikan nama item/barang sudah benar')
                elif c == 2:
                  ts.reset_transaction()
                elif c == 0:
                  break
                else:
                  print('\nMohon ulangi!. Pastikan:\n*Bilangan yang Anda masukan bilangan bulat 1-3!')
              except:
                print('\nMohon ulangi!. Pastikan:\n*Bilangan yang Anda masukan bilangan bulat!')
              
          else:
            print('Maaf, item/barang belum ditambahkan. Silahkan pilih menu tambah item/barang!')
        elif a == 4:
          ts.check_order()
        elif a == 5:
          ts.total_price()
        elif a == 0:
          break
        else:
          print('Mohon ulangi!. Pastikan:\n*Bilangan yang Anda masukan bilangan bulat 1-6!')
    except:
      print('Mohon ulangi!. Pastikan:\n*Bilangan yang Anda masukan bilangan bulat!')
  
main()